name: deploy

on: [deployment]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      username: '${{secrets.username}}'
      password: '${{secrets.password}}'
      passphrase: '${{secrets.passphrase}}'
      gpgKeyID: '${{ secrets.gpgKeyID }}'
      MAVEN_GPG_SIGN_KEY: '${{secrets.MAVEN_GPG_SIGN_KEY}}'

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12.x
    - name: setup
      run: |
        echo -e "$MAVEN_GPG_SIGN_KEY" | gpg --import --batch -
        echo -e "use-agent\npinentry-mode loopback" >> $HOME/.gnupg/gpg.conf
        echo "allow-loopback-pinentry" >> $HOME/.gnupg/gpg-agent.conf
        echo RELOADAGENT | gpg-connect-agent
        gpg --keyring secring.gpg --export-secret-keys > $HOME/.gnupg/secring.gpg --passphrase=$passphrase
        mkdir -p $HOME/.gradle && echo -e "nexusUsername=$username\nnexusPassword=$password\nsigning.keyId=$gpgKeyID\nsigning.password=$passphrase\nsigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg" > $HOME/.gradle/gradle.properties
    - name: deploy
      run: ./gradlew clean build uploadArchives closeAndReleaseRepository
