name: Deploy

on: deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      username: '${{secrets.username}}'
      password: '${{secrets.password}}'
      passphrase: '${{secrets.passphrase}}'
      MAVEN_GPG_SIGN_KEY: '${{secrets.MAVEN_GPG_SIGN_KEY}}'

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Setup maven
        run: |
          echo -e "$MAVEN_GPG_SIGN_KEY" | gpg --import --batch -
          gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys $gpgkey
          rm -rf $HOME/.m2
          mkdir -p $HOME/.m2
          echo -e "<settings>\n<servers>\n<server>\n<id>ossrh</id>\n<username>$username</username>\n<password>$password</password>\n</server>\n</servers>\n</settings>" > $HOME/.m2/settings.xml

      - name: Deploy on maven central
        run: |
          mvn -q clean deploy -Dgpg.passphrase=$passphrase
        working-directory: java
